title = "Mani Kumar"
languageCode = "en-us"
baseurl = "https://manid2.github.io/"
canonifyurls = true

[pagination]
  pagerSize = 20

[module]
  [[module.imports]]
    path = "github.com/manid2/hugo-xterm"

[params]
  centerTheme = true
  showMenuItems = true
  favicon = "/images/favicons/favicon.ico"
  showBreadCrumbs = true
  toc = true
  copyrightUserUrl = "https://twitter.com/mani_d2"
  copyrightUserText = "mani_d2"

[params.twitter]
  creator = "mani_d2"

[params.site_verification]
  google = "dRxlQUCTcreupAiAU9R-WcImzIL5ZkXVFT4PVPDJl6Y"
  bing = "F82FFC97299503C8B6340178FE5F1EFA"
  yandex = "146d77656fc95385"
  naver = "e3b93136c43487a12e31584cf30306a269137968"

[languages]
  [languages.en.params]
    copyright = "© Mani Kumar"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"

      [[languages.en.menu.main]]
        identifier = "support"
        name = "Support"
        url = "/support/"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
